coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0%
        base: auto 
        paths: null
        branches: 
          - master
        if_not_found: success
        if_ci_failed: error
        informational: false
        only_pulls: false